

name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pygame

      - name: Build with Nuitka
        run: |
          nuitka --standalone --onefile --output-dir=dist main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 16bit-pygame-${{ matrix.os }}
          path: dist/
